- constants/chainIds.js
- constants/extraRpcs.json
Adds Crystaleum (💎) network
Official Site: https://crystaleum.org/
Chain ID: 103090
(PR 1213 of official chain list https://github.com/ethereum-lists/chains/pull/1213)
> Add Crystaleum 💎

- constants/extraRpcs.json
Hi, we're adding our full archive public node to the list of RPCs, and also want to ask if you know the reason why it's saying on the website that all the non-SSL RPCs are down whilst they're also operational?
Thanks.
> update nova network rpcs

- components/chain/index.js
- pages/chain/[chain].js
- pages/sitemap.xml.js
Currently, chainlist accesses chaindata for a network by calling `networkId`, rather than `chainId`
1) this is a bug, as these are two different things (bug has gone undetected bc `chainId == networkId` in most EVM networks). This is not true for 31 of the networks in your data source (https://chainid.network/chains.json)
Some networks have equivalent networkIds but differing chainIds (most notably ethereumclassic, which has a `networkId=1`), where this proves to be a bug seen in two flows
- clicking on Ethereum Classic (or other networks w `networkId=1` from homepage directs user to Ethereum)
- https://chainlist.org/chain/61 (Ethereum Classic's chainId) returns internal server error
See side by side of bug fix below
> bug fix: change networkId calls to chainId

- constants/extraRpcs.json
Add Blast APIs for Polygon Testnet, Ethereum Goerli, Fantom Testnet, Avax Testnet, Moonbase Alpha and Palm Mainnet
> Add Blast APIs for Multiple Networks

- constants/extraRpcs.json
add new RPC URL to Ethereum Mainnet, service provider is Unifra (https://www.unifra.io/)
> add new RPC URL to Ethereum Mainnet

- constants/extraRpcs.json
Maybe that works, I don't know if you use default the 8545 port or not. And it's a Hyperledger Besu node, which has a different JSON formatting (Multi Lines)
> update etc-network.info ETC RPC

- constants/extraRpcs.json
Fuse recently got a high-performance public RPC from Chainstack, it has now been included on here to account.
> Added Chainstack endpoint to Fuse

- constants/extraRpcs.json
Migrated to cosmosia subdomain
Eg., https://jsonrpc-evmos-ia.notional.ventures => https://jsonrpc-evmos-ia.cosmosia.notional.ventures
> update Notional Evmos Public Endpoint

- constants/extraRpcs.js
Flashbots RPC does not track. Can be confirmed in the codebase at https://github.com/flashbots/rpc-endpoint
> Update extraRpcs.js - Flashbots RPC does not track

- constants/extraRpcs.js
- created a privacy statement by RPC provider as to not repeat statement multiple times.
- also include privacy statements for non-tracking providers
- duplicate provider information wherever applicable
- cite source for ease of checking / updating
also quick note about publicnode.com privacy. It appears the existing statement was taken from publicnode.org (stellar node provider). publicnode.com privacy statements do not load, but upon further research it looks like they are run by allnodes.com
> update rpc privacy statements

- constants/extraRpcs.js
Hi team
The sps mainnet's rpc is migrated into
https://rpc.ssquad.games/
Thanks
> Migrate sps mainnet into new rpc URI

- constants/extraRpcs.js
Ethercluster is being retired in favor of an endpoint being operated by Rivet.
Also the BlockScout ETC endpoint should never have been public.
> Updating ETC Coop's public endpoints

- constants/chainIds.json
- constants/extraRpcs.js
Removing RPC for chain 2020 as it is not representing Public Mint chain.
https://publicmint.com
https://publicmint.com/privacy-policy
> Remove wrong rpc

- constants/extraRpcs.js
Add BlockPI Public RPC on Ethereum from https://public.blockpi.io/
> Add BlockPI Public RPC on Ethereum

- constants/extraRpcs.js
`https://payload.de`
`https://payload.de/privacy/`
> Add payload.de RPC & privacy policy to the Ethereum extraRpcs.js

- constants/extraRpcs.js
Adding more public RPCs from BlockPI https://public.blockpi.io/
https://public.blockpi.io/
> Adding more public RPCs from BlockPI

- constants/extraRpcs.js
Fix the Goerli endpoint location. (`https://goerli.blockpi.network/v1/rpc/public` is for eth's goerli not arbitrum's goerli)
And add more Public RPCs for other chains. Thanks!
> Add more Public RPCs from BlockPI

- constants/extraRpcs.js
Adding two more BlockPI public endpoints. One is Eth Sepolia. And Scroll Pre-Alpha chain is new in this file.
Thanks!!!
> Add BlockPI public endpoint for Eth Sepolia and Scroll Pre-Alpha

- constants/extraRpcs.js
Add another Wanchain Rpc running in Flux OS.
https://runonflux.io
https://github.com/wanchain/go-wanchain/blob/develop/COPYING
This is an unrestricted open RPC service created by wanchain official and flux in cooperation.
This is the wanchain official tweet about this:
https://twitter.com/wanchain_org/status/1621132361785135105?s=20&t=u2v8W54QozWrzJyPzc3CoA
> Add another RPC for wanchain

- pages/api/chain/[chain].js
Add endpoint to return Chain RPC data by slug or chain id. 
This allows users to dynamically pull and use the list of public RPC for a specific chain.
I wanted to update `pages/chain/[chain].js` but we can't return a JSON page from `getStaticProps`. We could also simply upload the json file in `/public` but we'd need a cron to update them on a regular basis so that's why I added this endpoint.
Note: we'll need to enable CORS access if we want people to access this API endpoint from the outside. 
ex:
```
GET https://chainid.network/api/chain/1
GET https://chainid.network/api/chain/eth
```
> RPC endpoint

- constants/extraRpcs.js
https://www.publicnode.com (RPC is not new. Already presented in Polygon, Ethereum, Avalanche, Evmos)
https://www.publicnode.com/privacy
> Add PublicNode RPC Endpoints for Fantom & BSC

- constants/extraRpcs.js
I don't know if this is happening only to me, but for some reason when I submit a transaction to Arbitrum using the Omnia RPC it fails with the following error:
```
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{}}'
```
The transactions also appear as failed on Metamask:
However, when they show as successful on Arbiscan. As you can see from the screenshot, this happens with every dApp. Whether the transaction originated from `localhost:3000` or `arbiscan.io`, it shows as failed (but all succeeded).
This error doesn't happen with the official Arbitrum RPC endpoint. I suggest to remove the Omnia endpoint.
Does anyone else have the same error?
> Remove the Omnia RPC on Arbitrum

- constants/extraRpcs.js
https://gov.edgewa.re/discussion/6607-public-rpc-and-bootnodes-jelliedowl
(JelliedOwl, the contributor to Edgeware DAO do not store any user information and they do not parse it to any third party.)
> Add an RPC for Edgeware

- constants/extraRpcs.js
add GetBlock endpoint 
https://arbitrum.getblock.io/api_key/mainnet/
> Add GetBlocks RPC endpoints to the list

- constants/extraRpcs.js
Scroll Pre Alpha has network ID 534354 and Scroll Alpha has network ID 534353 - we previously added by mistake on a wrong ID.
https://blastapi.io/
https://blastapi.io/privacy-policy
> Add BlastAPI to Scroll Alpha and fix previous Network ID error

- constants/extraRpcs.js
New RPC address for GasHawk, see: https://www.gashawk.io/#/setup
> Updated RPC URL for GasHawk

- constants/extraRpcs.js
+ Chain 6
+ Chain 63
https://etc-network.info
etc-network.info privacy policy is already listed.
Just adding already supported RPC providers testnet RPC endpoints.
> Add ETC Testnets

- constants/extraRpcs.js
https://croswap.com
https://croswap.com/legal/privacy/
> Add Croswap Arbitrum RPC & Add privacy to Croswap Cronos RPC

- constants/extraRpcs.js
Updated existing gateway.fm RPC urls for Gnosis and Chiado with recent values
https://gateway.fm/
https://gateway.fm/privacy-policy/
> Update gateway.fm RPCs for Gnosis and Chiado

- constants/extraRpcs.js
> resort and correct RPC URL etc-network.info

- components/header/index.js
Currently you cannot re-use the search bar once you navigate to a `/chain/ ` page. This minor inconvenience is fixed with this simple pr.
> Fix navigation bug on /chain page

- constants/chainIds.json
This ensures the correct logo gets loaded from icons.llamao.fi.
> Add chain IDs for Zilliqa

- constants/extraRpcs.js
https://tenderly.co/
https://boba.network
https://tenderly.co/privacy-policy
Added in the beginning, because these are now the recommended RPCs, please let me know if that's not supported.
> Add Tenderly RPCs for Boba ETH Mainnet

- constants/extraRpcs.js
https://gateway.fm/
https://gateway.fm/privacy-policy/
> Add gateway.fm RPC for Arbitrum and Optimism

- components/AdBanner/index.js
Banners would sometimes "flash" as there's some randomness involved in the shuffle function and the image rendered on the server can be different from the image rendered on the client
> fix: random banners hydration issue

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for Meter and Zetachain

- constants/extraRpcs.js
- added Tenderly Ethereum Mainnet RPCs
- added Tenderly Ethereum Goerli RPCs
- added Tenderly Ethereum Sepolia RPCs
- added Tenderly Polygon Mainnet RPCs
- added Tenderly Polygon Mumbai RPCs
- fixed Tenderly Boba RPCs (HTTP -> HTTPS)
https://tenderly.co
https://tenderly.co/privacy-policy
> Update extraRpcs.js with Tenderly.co RPCs

- constants/extraRpcs.js
> Add optimism.meowrpc.com and arbitrum.meowrpc.com

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for Arbitrum-goerli

- constants/extraRpcs.js
> Add polygon.meowrpc.com to extraRpcs.js

- constants/extraRpcs.js
Starting from July 24th, 2023 the current endpoint will be disabled, this PR updates it with the new one listed in the announcement.
https://etccooperative.org/posts/2023-06-24-important-announcement-migrate-the-etc-and-mordor-rpc-endpoints-by-july-24-2023-en
> Update Ethereum Classic Mordor network RPC endpoint

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for polygon-zeEVM

- constants/extraRpcs.js
we have added some rpc and the following answers remain the same as last time
https://zan.top/home/node-service
https://a.zan.top/static/Privacy-Policy.pdf
> Update extraRpcs.js : add arb and opt

- constants/extraRpcs.js
> Update extraRpcs with new blockpi public endpoint for zksync-era-testnet

- constants/extraRpcs.js
The website is being worked on and it will be up soon.
No privacy policy
I am running archival nodes and would like to provide RPC endpoints as a public good service for other devs to use. There is no tracking and rate limits. It would be nice if my rpc endpoints could be added to the list. Thank you!
> add rpc endpoints from notadegen.com

- constants/extraRpcs.js
> Update extraRpcs with new blockpi public endpoint for zksync-era

- constants/extraRpcs.js
https://meowrpc.com/
https://privacy.meowrpc.com/
> Add base.meowrpc.com to extraRpcs.js

- constants/extraRpcs.js
Update pocket network bnb/bsc public RPC
https://www.pokt.network/
https://www.pokt.network/privacy-policy/
> Pocket: Update bnb/bsc public endpoint

- constants/extraRpcs.js
bitstack.com
https://bitstack.com/#/privacy
> change bitstack api to openapi for support Cross-Domain

- constants/extraRpcs.js
Also updates ETH goerli and sepolia rpc endpoints from notadengen.com
Under construction
No privacy policy
I am running archival nodes and would like to provide RPC endpoints as a public good service for other devs to use. There is no tracking and rate limits. It would be nice if my rpc endpoints could be added to the list. Thank you!
> Add BASE chain RPC endpoints from notadengen.com

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for BSC-Testnet

- constants/extraRpcs.js
we have added some rpc and the following answers remain the same as last time
https://zan.top/home/node-service
https://a.zan.top/static/Privacy-Policy.pdf
> Update extraRpcs.js : add avax and polygonzkevm in zan

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for AVAX-fuji

- constants/extraRpcs.js
Fixed an issue with incorrect URL configuration of zan in avalanche
> 🚨 Update extraRpcs.js :fix avax url

- constants/extraRpcs.js
- https://www.gravitybridge.net/
- https://www.chandrastation.com/
- https://nodestake.top/
- https://dexvaults.com/
Unable to find (RPC-specific) privacy policies for any of the providers.
These are popular RPCs for the Canto blockchain.
> add canto RPCs

- constants/extraRpcs.js
https://www.lavanet.xyz/
https://www.lavanet.xyz/privacy-policy
N/A
Your RPC should always be added at the end of the array. =>
Please note - Lava in partnership with the Evmos team was tasked with providing incentivized public RPC endpoints as the default RPC for Evmos ecosystem. This PR adds ipRPC endpoint to rpc lists on 9001. The _intention_ is for Lava to be the default RPC for Evmos.
> add lava ipRPC to evmos rpc list

- constants/extraRpcs.js
At Evmos, we have engaged in a new cooperation with Lava Network who provide amazing RPC services! We would like to make this endpoint the default RPC endpoint when users connect to the Evmos network using MetaMask.
Lavanet website: https://www.lavanet.xyz/
Also if you could point me to, where I can submit a corresponding PR for the testnet configuration, I would be very grateful 🙏
> imp: add Lava RPC endpoint as default for Evmos chain

- constants/extraRpcs.js
https://0base.vc
N/A
This needs to be added for a reliable JSON RPC service in EVMOS.
> Add 0base.vc's EVMOS json-rpc.

- constants/extraRpcs.js
> Add Evmos RPC by NodeStake

- constants/extraRpcs.js
TC Network:
Website: https://tcnetwork.io
Explorer: https://explorer.tcnetwork.io
We are providing the RPC as public goods service
> add TC Network RPC to Evmos

- constants/extraRpcs.js
1RPC supports more networks:
- Gnosis Mainnet
- Ethereum Holesky
- Ethereum Sepolia
- Manta Mainnet
- zkSync Era Mainnet
Link the service provider's website (the company/protocol/individual providing the RPC): https://www.1rpc.io
Provide a link to your privacy policy: https://www.1rpc.io/tou
> 1RPC now supports more networks

- constants/extraRpcs.js
> Add Evmos testnet RPC by NodeStake

- constants/extraRpcs.js
> Add alkadeta Evmos json-rpc

- constants/chainIds.json
To fix the issue of the Conflux icon not displaying due to the absence of the chainid of Conflux.
https://confluxnetwork.org/
> add chain_id for Conflux in chainIds.json

- constants/extraRpcs.js
> Add Kalia json rpc

- constants/extraRpcs.js
> Add evmos RPC

- constants/extraRpcs.js
>   1 Update extraRpcs.js with new blockpi public endpoint for x1-testnet

- constants/extraRpcs.js
Note deprecated Ethereum Classic testnet chains to prevent replay attacks.
+ Chain6 Kotti (PoA deprecated in 2022 for Chain63)
+ Chain62 Morden (PoW with old 2016 baggage, replaced by Chain63 in 2019).
Chain 63 Mordor is the preferred testnet for Ethereum Classic. Supported by core-geth, the main Ethereum Classic client.
https://etclabscore.github.io/core-geth/
> Note Deprecated Chains 6, 62

- constants/extraRpcs.js
Removing endpoint https://rollux.public-rpc.com because it is unstable and has been negatively impacting user experiences for weeks with no resolution. Will consider adding again once issue is confirmed resolved and service is stable.
-- Syscoin Foundation, Rollux team
> Rollux: Remove malfunctioning third-party endpoint

- constants/extraRpcs.js
> add ecmos testnet rpc

- constants/extraRpcs.js
+ Update to reflect limited tracking for RPC endpoints.
+ Remove offline RPC endpoints
Not new. Update to reflect current privacy statement.
Existing privacy statement at ".etcnetworkinfo"
Note: I'm not associated with RPC endpoints, I am simply cleaning up the Ethereum Classic RPC pages for the general public as we are seeing increased adoption on the network.
> Update: etc-network.info Limited Tracking setting

- constants/extraRpcs.js
This PR adds the privacy policy for [Rivet](https://rivet.cloud/)'s Ethereum Classic RPC endpoint. From their [FAQ](https://rivet.cloud/FAQ's):
> Q: What can you do with my request data?
> A: Request data contains substantially more information than what appears on the public ledger. Users' wallet addresses, token balances, web3 browsing activity along with PII that can be connected back to web2 services like Facebook. If you or your users' idiosyncratic usernames, email addresses and even IP addresses can be tied to activity on Facebook or Google, web3 might become just another vector for information-miners, advertizers and oppressive regimes to exploit. That's why we've created an armored privacy policy that we promise to stand over on principle. We will never sell or willingly share …
> Add Rivet's privacy policy

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for ETH-Holesky

- constants/extraRpcs.js
N/A
All RPC are public for all users.
Update the RPC info from Official Fusion Network. All the existing community rpc such as anyswap / fsn.dev are not function. Hence we request to delete those rpc in order to not misleading user
> update fusion network rpc

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for ZetaChain-Evm

- constants/extraRpcs.js
https://www.allthatnode.com/
https://www.allthatnode.com/privacypolicy.dsrv
> Update extraRpcs.js with new All That Node endpoints for ZetaChain

- constants/extraRpcs.js
https://itrocket.net/
https://itrocket.net/privacy-policy/
Edited the endpoints upon the project team request and updated policy data with this PR.
> Update: ITRocket endpoints and Privacy Policy

- constants/extraRpcs.js
https://polysplit.cloud/
https://polysplit.cloud/privacy
We fixed issues happened previously, did not expect such high traffic
> fix polysplit

- constants/extraRpcs.js
https://rpcgrid.com/ (under construction)
`Only strictly functional data is automatically collected by the RPC. None of this data is directly exported or used for commercial purposes.`
RpcGrid provides free and unlimited access for ZetaChain RPC & WS.
> Add zeta.rpcgrid.com RPCs (+WS) for ZetaChain

- constants/extraRpcs.js
https://gasswap.org
https://docs.gasswap.org/gasswap/public-node#privacy-policy
> Add blast.gasswap.org

- constants/extraRpcs.js
- Updated the 4 Stateless RPC URLs to be readable completely in the chart (from a UUID to "demo")
- Moved the Stateless Arbitrum One URL into Arbitrum One since it was accidentally in Arbitrum Goerli
> Update Current Stateless RPC URLs

- constants/chainIds.json
- constants/extraRpcs.js
Adding new Perp Chain Hubble Exchange(Hubblenet). The PR is still open on [ethereum-lists/chains](https://github.com/ethereum-lists/chains/pull/4486) to add this chain to the list.
https://www.hubble.exchange
Terms & Condition don't have anything related to privacy policy but the RPC don't collect any information of the users and it's the public and only one rpc atm.
> feat: add hubble exchange chain - hubblenet

- constants/extraRpcs.js
The RPC website https://tornadoeth.cash is a scam tornado cash UI fork that steals user's deposits via deposit note being sent to the rpc's header value
Proof
Also related with:
https://github.com/MetaMask/eth-phishing-detect/pull/29903
> Delist scam rpc ( tornadoeth.cash )

- constants/extraRpcs.js
https://infura.io/
https://consensys.io/privacy-policy for Infura
> add Linea RPC urls

- constants/extraRpcs.js
Ethereum: https://app.subquery.network/explorer/project/0x04/overview
Base: https://app.subquery.network/explorer/project/0x06/overview
https://subquery.foundation/public-rpc-terms
> Added SubQuery RPC for Blast & Ethereum

- constants/extraRpcs.js
Updated Subquery's Ethereum & Base endpoints
Added Subquery Polygon, Arbitrum, and Eth Sepolia
---
https://subquery.network/rpc
https://subquery.network/privacy
> SubQuery Endpoint changes

- constants/extraRpcs.js
I've rearranged the addresses for my RPCs - this corrects them to the new values.
Chainlist is also showing wss://edgeware.jelliedowl.net, which is NOT an EVM endpoint.  I'm not sure where it's pulling that data from, since I can't find it in this repo?
(Onfinality has stopped providing an RPC for Edgeware. I think their RPC address is dead and not coming back, but I'm not going to decided that it should be removed.)
I don't have a website to link to - I'm just a community member providing some RPCs.
> Update Jelliedowl Edgeware RPCs

- constants/extraRpcs.js
> Addint Tatum RPC node - Klaytn

- constants/extraRpcs.js
> Adding Tatum RPC Node - Palm

- constants/extraRpcs.js
I've removed broken/bad url from blastapi.io on Avalanche
The correct one is: **https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc**, which is already set there.
The **removed url** is just the link to our web public api page
> Remove broken blastapi.io url

- constants/extraRpcs.js
The management of POKT's RPCs has been transferred from POKT to Grove, and the RPC URLs have changed. Therefore, we will be updating to the new valid URLs.
The new RPC to be added is the official WebSocket URL of Oasys.
https://www.oasys.games/
https://docs.oasys.games/docs/staking/rpc-endpoint/1-1-rpc-endpoint#mainnet
https://www.oasys.games/app/uploads/2024/03/Oasys-Privacy-Policy_Mar2024.pdf
> Updated extraRpcs.js for Oasys.

- constants/extraRpcs.js
https://pollum.io/
The RPCs are public.
N/A
> Added Pollum services Rpc for syscoin and rollux, mainnet and testnet

- constants/extraRpcs.js
Building our landing page [here](https://sigmacore.io), we are the same team as [Stakingverse](https://stakingverse.io) with staking services for LUKSO and Ethereum. For now our RPC is free, we will add paid tiers for enterprise later on.
[https://sigmacore.io/privacy-statement.pdf](https://sigmacore.io/privacy-statement.pdf)
> Add SigmaCore RPC for LUKSO blockchain

- constants/extraRpcs.js
Add BSquared RPC endpoint
https://www.bsquared.network/
> Add BSquared RPC endpoint

- constants/extraRpcs.js
Add Etherlink mainnet. Currently, the network is not launched yet. More information, including a privacy policy, will be added once everything goes live
https://etherlink.com
None at the moment. We will create a follow-up PR as soon as we have more precise information to provide.
> Update extraRpcs.js -- Etherlink mainnet

- constants/extraRpcs.js
The registered set of RPCs for network 19 (Songbird) is defined in:
https://github.com/ethereum-lists/chains/blob/40c4b1a0a33ecc656c17f16ec2b0930c62b2ba51/_data/chains/eip155-19.json#L5
`chainlist/constants/extraRpcs.js` defines an RPC outside of that registered set. 
https://github.com/DefiLlama/chainlist/blob/0b99ad83072207b649c057b593237752ba222d5f/constants/extraRpcs.js#L2218
This is also the default Chainlist chooses, leading to warnings when adding the network via Chainlist to wallets like Metamask etc.
Perhaps the simplest solution here is to just remove this RPC from `extraRPCs.js`, which I have done in this PR. This should let Chainlist use the registered RPCs defined in `ethereum-lists/chains`.
Please let me know if this is not the case, and I will modify the PR accordingly. …
> Remove non-registered RPC for network 19

- constants/extraRpcs.js
Kaia Testnet Kairos RPC update(Kaia is klaytn's new name)
Kaia Testnet Kairos Launch Announcement Blog: https://klaytn.foundation/kaia-testnet-kairos-launch/
> Kaia testnet kairos RPC update

- constants/extraRpcs.js
* Updated the Klaytn Testnet url https://klaytn.foundation/kaia-testnet-kairos-launch/
* Updated the Allthatnode urls of Klaytn https://www.allthatnode.com/klaytn.dsrv
> Updated Klaytn Testnet endpoint and allthatnode urls

- constants/extraRpcs.js
Not finish right now. And RPC provided automaically by Avacloud Subnet solution
> Add PLYR PHI mainnet

- constants/extraRpcs.js
Add WebSocket endpoint for Graffiti RPC
https://graffiti.farm
https://graffiti.farm/privacy-policy/
> Update extraRpcs.js - Graffiti WebSocket Endpoint

- constants/extraRpcs.js
https://chainstack.com/
https://www.liquify.io/
https://dubiw3zgo51jg.cloudfront.net/pp.pdf
> added Zircuit RPC endpoints

- constants/extraRpcs.js
These RPCs won't be maintained anymore
https://pollum.io/
N/A
N/A
> Removed the Pollum rpcs with pollum.services dns

- constants/extraRpcs.js
https://www.hashkey.cloud/
https://group.hashkey.com/en/privacy-policy
> Add HashKey Chain Testnet RPC

- constants/extraRpcs.js
Fix missing semicolon removed in:
https://github.com/DefiLlama/chainlist/commit/6f6cdd38f400253050a892339ef308e606975d84
> Fix missing semicolon in extraRpcs.js

- constants/extraRpcs.js
Add OriginStake RPC testnet for Story Protocol
Website: https://originstake.com
Verified by StakingReward: https://www.stakingrewards.com/provider/originstake
https://originstake.com/privacy
> Update extraRpcs.js - Add RPC testnet for Story Protocol

- constants/extraRpcs.js
https://porters.xyz/
https://porters.xyz/tos - note that this has been updated since the last version, with IP and any other tracking used for testing removed. For clarity, the reference to public keys being stored internally refers to accounts created on porters, so does not apply to public endpoints since that is running on our own PORTERs account. 
Feel free to let me know if you have any questions on this. Thanks!
> PORTERs endpoints updates (hekla and TOS)

- constants/extraRpcs.js
https://services.tech-coha05.xyz
https://services.tech-coha05.xyz/privacy_policy.html
It helps more RPCs come to Story networks becuz there is not much avl RPCs then.
> Add Story Testnet RPC

- constants/extraRpcs.js
We are shutting down our public ws endpoint within the week, also need to remove wss://ws.mainnet.taiko.xyz but unsure where to do so
> Remove Taiko ws endpoint

- constants/extraRpcs.js
- Tenderly Polygon Amoy Node RPC
- Tenderly Avalanche Mainnet Node RPC
- Tenderly Arbitrum Node RPC
- Tenderly Arbitrum Nova Node RPC
- Tenderly Arbitrum Sepolia Node RPC
- Tenderly Blast Node RPC
- Tenderly Optimism Sepolia Node RPC
- Tenderly Holesky Node RPC
- Tenderly Base Sepolia Node RPC
- Tenderly Taiko Node RPC
- Tenderly Taiko Hekla Node RPC
- Tenderly Taiko Node RPC
- Tenderly Mode Node RPC
- Tenderly BOB Node RPC
- Tenderly Fraxtal Node RPC
- Tenderly Immutable Node RPC
- Tenderly Lisk Node RPC
https://tenderly.co
https://tenderly.co/privacy-policy
> Add Tenderly.co Node RPCs

- constants/extraRpcs.js
Add OriginStake ZeroGravity Newton Testnet RPC
Website: https://originstake.com/
Verified by StakingReward: https://www.stakingrewards.com/provider/originstake
https://originstake.com/privacy
> Update extraRpcs.js - Add OriginStake ZeroGravity Newton Testnet RPC

- constants/extraRpcs.js
[https://citrea.xyz](https://citrea.xyz)
Didn't add a privacy policy since other default RPC's for chains didn't have one. If this is a must I can make another commit.
> add Citrea testnet RPC

- constants/extraRpcs.js
https://service.josephtran.xyz/testnet/vana/services
https://service.josephtran.xyz/testnet/privacy-policy
Although I have provided a privacy policy link, I'd like to emphasize that this RPC node adheres strictly to best practices in data protection. No personal data is collected or stored from RPC requests. The node only processes blockchain-related queries without retaining any user-specific
> Add VANA Testnet RPC

- constants/chainIds.json
This PR will add the Lisk Chain ID to the ChainID constants.
Lisk is already merged into Ethereum Chainlist:
https://github.com/ethereum-lists/chains/pull/4988
RPC for Lisk is already available: 
https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.js#L5545
Thanks!
> Add Lisk Chain ID

- constants/extraRpcs.js
https://services.tech-coha05.xyz/
https://services.tech-coha05.xyz/privacy_policy.html
For user more choice when some rpcs get congestion
> add Coha05 vana testnet rpc

- constants/extraRpcs.js
https://blastapi.io/chains/rootstock
Already included in chainlist
> Add Roostock BlastAPI endpoint

- constants/extraRpcs.js
- Main website: https://stakely.io/
- Fantom JSON-RPC load balancer: https://stakely.io/web3-api-load-balancer/fantom?type=json-rpc
- Taiko Mainnet JSON-RPC load balancer https://stakely.io/web3-api-load-balancer/taiko?type=json-rpc 
> feat: added stakely json-rpc for taiko and fantom

- constants/extraRpcs.js
Tatum currently doesnt provide free public RPC endpoints.
https://tatum.io/nodes
So, removing from the chainlist accordingly. 
Thanks.
> Updated Kaia chain extraRpcs

- constants/extraRpcs.js
https://cheesechain.xyz
CheeseChain has been added in https://chainid.network/
https://chainid.network/chain/383353/
> Add CheeseChain RPCs

- constants/extraRpcs.js
OnFinality has removed Harmony's RPC, so this endpoint is no longer valid: 
`https://harmony.api.onfinality.io/public`
> Delete OnFinality RPC endpoint for Harmony

- constants/extraRpcs.js
- remove deprecated rpc addresses
- added 0.48.club, it is different from rpc-bsc.48.club in that eth_gasPrice returns 1wei. Here is its usage description https://docs.48.club/privacy-rpc/0-gwei-rpc & https://docs.48.club/48-soul-point
- added websocket protocol rpc, btw wss://0.48.club/ws/ also works
> update 48Club rpc url

- constants/extraRpcs.js
[https://dexrouting.com](https://dexrouting.com/)
[https://dexrouting.com/privacy](https://dexrouting.com/privacy)
> Add dexrouting Canto RPC

- constants/extraRpcs.js
> add two iotex rpc

- constants/chainIds.js
I think there is still an inconsistency between the normalized name and the chainId mapping. 
The icon logo [server](https://api.llama.fi/chains) returns `sapphire`.
```json
{
"gecko_id": null,
"tvl": 4693817.56340488,
"tokenSymbol": "ROSE",
"cmcId": null,
"name": "Sapphire",
"chainId": 23294
},
```
Or maybe we need to rename "sapphire" [here](https://github.com/DefiLlama/defillama-server/blob/2eed7f3275bfed16cab2118cd3250923b79032dc/defi/src/utils/normalizeChain.ts#L29)?
> Fix Oasis Sapphire shortname in mapping of chainIds

- constants/chainIds.js
Adding missing hydration chain id. Seems like icon is also missing yet i can see correct icon here:
https://github.com/DefiLlama/icons/blob/v2/assets/chains/rsz_hydration.jpg
Any idea? 
See:
https://chainlist.org/chain/222222
https://chainid.network/chain/222222/
> add hydration chain id

- constants/extraRpcs.js
QuickNode: https://www.quicknode.com/docs/arbitrum-nova#endpoint-authentication-options
https://www.quicknode.com/docs/arbitrum-nova/eth_accounts
Alchemy: https://docs.alchemy.com/reference/arbitrum-nova-api-quickstart#3-make-your-first-request
Already exist in the repo
> feat: add alchemy and quiknode rpcs for nova

- constants/extraRpcs.js
https://docs.kaia.io/references/public-en/#testnet-kairos-public-json-rpc-endpoints
https://docs.kaia.io/misc/terms-of-use/
> Updated Kaia RPC endpoint

- constants/chainIds.js
- constants/extraRpcs.js
https://www.conduit.xyz/
`rpc.powerloom.network.	300	IN	CNAME	rpc-powerloom-mainnet-hdsv5hx40a.t.conduit.xyz.`
https://www.conduit.xyz/privacy-policy
_Note: Merged chainid with lists repo as well:_  https://github.com/ethereum-lists/chains/pull/6477
> Add Powerloom Mainnet

- constants/extraRpcs.js
https://callstatic.com
https://callstatic.com/privacy-policy/
\-
> Add callStatic Sonic mainnet RPC

- constants/extraRpcs.js
Removed wrong rpc from kaia kairos testnet. its configured mainnet url instead of testnet. however onfinality doesnt provide free public kaia testnet url.
https://onfinality.io/networks/klaytn
> Removed wrong rpc from kaia kairos testnet

- constants/extraRpcs.js
https://dteam.tech/
Story mainnet preparation, pre-adding DTEAM Story mainnet RPC. Chain already registered.
> Add DTEAM Story mainnet RPC to extraRpcs.js

- constants/extraRpcs.js
https://dteam.tech/
Add an extra, third DTEAM Story Odyssey RPC. Chain already registered.
> Add an extra, third DTEAM Story Odyssey RPC to extraRpcs.js

- constants/extraRpcs.js
https://dteam.tech/
Add an extra, second DTEAM Story Odyssey RPC. Chain already registered.
> Add an extra, second DTEAM Story Odyssey RPC to extraRpcs.js

- constants/extraRpcs.js
https://dteam.tech
Add extra Story Protocol Odyssey testnet RPC. Chain already registered.
> Add DTEAM Story Odyssey RPC to extraRpcs.js

- hooks/useFilteredChains.jsx
- pages/index.js
I had some issues with the search being slow when changing the query frequently
This PR solves the issue by impl a new hook `useFilteredChains` which cleans up the `Home` page and improves the search filter logic
> refactor(Home): improve search filtering logic

- constants/extraRpcs.js
This update fixes the issue while adding 0g chain to metamask
> Updated the RPC to fix the issue while adding network

- components/RPCList/index.js
- components/chain/index.js
- pages/chain/[chain].js
Related to #1426
Add block gas limit display to each chain card.
* Add a new state variable `blockGasLimit` with a default value of 'Unknown'.
* Fetch the block gas limit data for each chain using the chain's RPC URL.
* Update the table in the chain card to include a new column for the block gas limit.
* Display the fetched block gas limit in the new column, or 'Unknown' if the data is not available.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/DefiLlama/chainlist/pull/1511?shareId=8a005e07-bf5d-4416-9545-681bc77e0d97).
> Add block gas limit in each chain card

- constants/extraRpcs.js
https://dteam.tech
https://dteam.tech/privacy-policy
> Add DTEAM Privacy Policy

- constants/extraRpcs.js
https://dteam.tech/
https://dteam.tech/privacy-policy
> Add Privacy Statement to DTEAM RPCs

- constants/extraRpcs.js
> Add Allnodes RPC to Unichain and Berachain

- constants/extraRpcs.js
https://docs.zircuit.com/dev-tools/rpc-endpoints
Your RPC should always be added at the end of the array. -> Official RPC, putting at front of array
> add zircuit load balanced rpc

- constants/extraRpcs.js
https://www.lavanet.xyz/
https://www.lavanet.xyz/privacy-policy 
> Add Lava RPC endpoints for movement

- constants/extraRpcs.js
https://www.conduit.xyz
`rpc-v2.powerloom.network.	300	IN	CNAME	rpc-powerloom-mainnet-v2-v52tbqo4if.t.conduit.xyz.`
https://www.conduit.xyz/privacy-policy
**_Note: Merged chainid with lists repo as well:_  https://github.com/ethereum-lists/chains/pull/6999**
Context for the new chain: https://x.com/Powerloom/status/1897669070688022845
`TL;DR: OP Stack has discontinued support for custom gas tokens. Powerloom has a new Arbitrum Orbit based chain with a new chainid but the same icon. The older chain will continue to run until migration is complete.`
> Add Powerloom Mainnet V2

- constants/extraRpcs.js
Celo is migrating to an L2 today. To provide a seamless experience for all users, we want to remove all RPC providers who have not been confirmed as day 1 launch partners
> Remove all RPC providers who are not day 1 launch partners for Celo L2

- constants/extraRpcs.js
I am adding the public endpoint of an existing RPC (Quicknode) to Sophon Mainnet and Testnet
> feat: add quicknode RPC for Sophon

- constants/chainIds.js
- constants/extraRpcs.js
The "nibiru" object that comes through the DeFiLlama API is missing its chain ID (6900) and doesn't work with standard Uniswap (or similar) TVL adapter helpers as a result. 
See 
- ➡️➡️ https://github.com/DefiLlama/defillama-sdk/pull/174
- https://github.com/ethereum-lists/chains/pull/7329
--- 
https://nibiru.fi
https://nibiru.fi/privacy-policy-nibiru.pdf
...
> fix(chain-nibiru): help populate "nibiru" in the LlamaProvider and ChainApi objects

- constants/extraRpcs.js
https://privacy.hyperflow.finance/
Adding it improves network resilience, ensures decentralization, and provides fallback options in case the default RPC becomes unavailable or slow. Even without special features, having multiple RPC endpoints is critical for infrastructure robustness, wallet reliability, and user access continuity.
> add coti rpcs

- constants/extraRpcs.js
add initverse mainnet rpc
https://www.initverse.org/
> add initverse mainnet rpc

- constants/extraRpcs.js
https://spectrumnodes.com/
https://spectrumnodes.com/privacy-policy
> Add Spectrum Nodes to RPC Providers

- constants/extraRpcs.js
This PR updates the existing RPC endpoint for `omplatform.com` from the old URL to the new canonical URL.
Updated RPC endpoint from `https://rpc-cnx.omplatform.com` to `https://rpc.omplatform.com`
The service provider has migrated to a new RPC endpoint URL. The new endpoint `https://rpc.omplatform.com` is the updated canonical URL for their RPC service.
> Update omplatform RPC endpoint

- constants/extraRpcs.js
No, removing deprecated rpcs that no longer work.
https://public.blockpi.io/
> remove deprecated public blockpi rpcs

- constants/extraRpcs.js
The default arbitrum sepolia rpc, when clicking "Add to metamask" is deprecated:
Metamask warning 
> According to our records the submitted RPC URL value does not match a known provider for this chain ID.
Curl check
```
curl -X POST https://arbitrum-sepolia.blockpi.network/v1/rpc/private \
-H "Content-Type: application/json" \
-d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'
{"jsonrpc":"2.0","error":{"code":-32000,"message":"Apikey not found"}}
```
Blockpi website check (sepolia greyed out):
https://blockpi.io/chain/arbitrum
> Update Arbitrum Sepolia RPC

- constants/extraRpcs.js
Please Add Tatum Abstract RPC endpoint
https://tatum.io/chain/abstract
https://tatum.io/privacy-policy
> Please Add Tatum Abstract RPC endpoint

- constants/extraRpcs.js
Please Add Tatum Monad Testnet RPC endpoint
https://tatum.io/chain/monad
https://tatum.io/privacy-policy
> Please Add Tatum Monad Testnet RPC endpoint

- constants/additionalChainRegistry/chainid-222888.js
- constants/additionalChainRegistry/chainid-2288.js
Add Moca Chain Testnet/Mainnet
https://github.com/ethereum-lists/chains/pull/7641  is live
icons "moca" {
"url": "ipfs://QmNqJnEL2Aj7pLKYnJwRnWGZFwUWTsvfZm8CofA8ztvD6J",
"width": 512,
"height": 512,
"format": "png"
}
is already used in https://github.com/ethereum-lists/chains/blob/master/_data/icons/moca.json that we committed before
> Add Moca Chain Testnet/Mainnet

- constants/extraRpcs.js
Add additional RPC endpoint for KultChain (chainId 220312).
New RPC: https://kultrpc.kultchain.com
This provides users with an alternative endpoint for better reliability
and redundancy.
> feat: add extra RPC for KultChain

- .gitignore
- constants/additionalChainRegistry/chainid-47382916.js
https://unipoly.network
https://coinmarketcap.com/currencies/unipoly/
https://rpc.unpchain.com
https://explorer.unpchain.com
https://unipoly.network/en/chain/article/terms-conditions
The RPC endpoint https://rpc.unpchain.com is the official public RPC for the Unipoly Chain Mainnet, operated and maintained by the Unipoly Core Development Team.
It is essential for dApp developers, wallets, and external services to connect to and interact with the UNP blockchain.
This RPC does not log or retain any personally identifiable information and exists solely to provide secure, …
> Unipoly Chain

- constants/additionalChainRegistry/chainid-756.js
- constants/additionalChainRegistry/chainid-757.js
This PR adds CAPX Mainnet and Testnet to chainlist. Both networks are EVM-compatible Layer 2 chains (Arbitrum Orbit rollups) built on Capx's infrastructure for AI agent deployment and tokenization.
**Website:** https://www.capx.ai/
**Native Currency:** CAPX (18 decimals)
**Features:** EIP155, EIP1559
- **RPC URLs:** 
- https://capx-mainnet.calderachain.xyz/http
- wss://capx-mainnet.calderachain.xyz/ws
- **RPC URLs:**
- https://capx-testnet-c1.rpc.caldera.xyz/http
- wss://capx-testnet-c1.rpc.caldera.xyz/ws
---
**Note:** This PR adds new chain configurations following the structure outlined in the [README](https://github.com/DefiLlama/chainlist#add-a-chain). 
**Privacy Policy:** https://docs.capx.ai/
> Add CAPX Mainnet and Testnet (Chain IDs 757 and 756)

- constants/extraRpcs.js
Celo Alfajores and Celo Baklava have been deprecated. Find all information here: https://docs.celo.org/infra-partners/notices/celo-sepolia-launch#celo-sepolia-testnet-launch
> Remove deprecated test networks Alfajores and Baklava on Celo
