DefiLlama/chainlist

- components/header/header.js
This PR is to add the URL search parameter feature which existed in an [earlier version](https://github.com/DefiLlama/chainlist/blob/ea313b47b83dc6434ef8412384c9d1b9342a43cd/pages/index.js#L108-L112), but has since been removed.
> Add URL search parameter

- utils/extraRpcs.json
> Add Hermes DeFi RPC (Harmony)

- utils/extraRpcs.json
https://www.bnb48.club/validation-node
> add bnb48 club rpc

- components/chains.js
- utils/extraRpcs.json
Add ezchain to network list 
info: https://ezchain.com/
> add ezchain

- utils/extraRpcs.json
Added a Fantom RPC endpoint from Pocket Network
https://fantom-mainnet.gateway.pokt.network/v1/lb/62759259ea1b320039c9e7ac
> Update extraRPCs.json w/ a FTM RPC Endpoint

- constants/extraRpcs.json
Just added the Harmony public RPC created by [Chainstack](https://chainstack.com). More details about this public RCP in [the Harmony forum here](https://talk.harmony.one/t/partners-chainstack/5736/7)
> adds Chainstack harmony public RPC

- constants/extraRpcs.json
Removal of obsolete RPC endpoints.
> Update Gnosis Chain

- constants/extraRpcs.json
**Changes:**
Added Ankr RPC Optimism mainnet endpoint url
**Official Site:**
https://www.ankr.com/protocol/public/optimism/
**Chain ID:** 10
**BREAKING CHANGE:** No
> feat: Added new Ankr Optimism RPC endpoint

- constants/extraRpcs.json
Source: https://docs.klaytn.foundation/dapp/json-rpc/public-en#service-provider-fantrie
> Added more RPC nodes for Klaytn mainnet

- constants/extraRpcs.json
Added the RPC from icecreamswap.com for the Bitgert Blockchain.
> added additional Bitgert RPC

- constants/extraRpcs.json
We want to add more RPC's for Evmos
> add more Evmos RPCs

- constants/extraRpcs.json
> add rpc for seele

- constants/chainIds.js
- constants/extraRpcs.json
> Add OM Chain

- constants/extraRpcs.json
rpc from https://wiki.karura.app/general/address-binding
> add karura rpc

- constants/chainIds.js
- constants/extraRpcs.json
https://developer.offchainlabs.com/docs/public_chains
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-42170.json
> Add Arbitrum Nova

- constants/extraRpcs.json
DECENTRALIZED RPC GATEWAY TO XDC.Network
Welcome to the fastest, free-est, and most reliable DECENTRALIZED RPC endpoint for the XinFin XDC network.
> RPC GATEWAY TO XDC.Network | Added XDCRPC.com

- constants/chainIds.js
- constants/extraRpcs.json
Please help to review, my pull request was merged: https://github.com/ethereum-lists/chains/pull/1451
> Add posichain rpcs

- constants/chainIds.js
- constants/extraRpcs.json
I added CCN and Beta.
Is the network icon is automatically updated?
If not, how can I upload the icon?
> Add CCN and Beta Networks

- constants/chainIds.js
- constants/extraRpcs.json
Ref: [https://github.com/ethereum-lists/chains/pull/1453](https://github.com/ethereum-lists/chains/pull/1453)
> Adding Chiado testnet

- constants/chainIds.js
- constants/extraRpcs.json
Add Dogechain
https://dogechain.dog/
> Add Dogechain

- constants/chainIds.js
- constants/extraRpcs.json
Let's show some support for the one [kekchain](https://t.me/kekchain)
> add kekchain RPC

- pages/index.js
Currently only network contains "test" will considered as test network only, this MR will add devnet as test network.
> Devnet also consider as test networks too

- constants/extraRpcs.json
add rpc for chainid 126, and the rpc are working
> add rpc for chainid 126

- constants/chainIds.js
> add kardiachain id

- constants/extraRpcs.json
Added new RPC URL for network 32520 (BitGert chain)
> add new rpc

- constants/extraRpcs.json
Sorry for the many pull requests ;)
> add geth and besu / fix CORS Origin issue

- constants/extraRpcs.json
Add Automata private RPC relay to chainlist. Please visit https://www.1rpc.io to get more details.
> Update extraRpcs.json to add Automata 1RPC

- constants/extraRpcs.json
See https://securerpc.com/ for details
> Add SecureRPC to Ethereum RPC list

- constants/extraRpcs.json
Related to https://github.com/DefiLlama/chainlist/commit/937ae75dd977f07c34adfa3e764a7704e0bf3b0f, I think it's a mistake in @realdealshaman changes.
> Remove duplicated rpc endpoints

- constants/extraRpcs.json
Adds slingshot RPC (app.slingshot.finance)
> Adds slingshot RPC to list

- constants/chainIds.js
Adds Canto network: https://www.canto.io
> Adds Canto

- constants/extraRpcs.json
Hey there - Shelley from the Alchemy team. Given our new chain support and rollouts, I added the latest Alchemy rpc URLs for all our chains (Ethereum, Polygon, Arbitrum, Optimism, Astar along with the testnets). Pls let me know if there are any questions, appreciate what you guys are doing at Chainlist :)
> Adding eth mainnet

- constants/extraRpcs.json
> Update extraRpcs.json(add new rpc for seele network )

- constants/extraRpcs.json
our nodes are getting rekt on traffic
> Removes slingshot rpc

- constants/chainIds.js
- constants/extraRpcs.json
- removing old chiado testnet
- adding new chiado testnet
> Chiado testnet reboot

- constants/extraRpcs.json
https://fusiondev.gitbook.io/fusion/build/quick-links
> Added 32659 Fusion Mainnet

- constants/extraRpcs.json
https://wiki.acala.network/build/development-guide/smart-contracts/get-started-evm/connect-to-a-node/use-metamask-with-evm+#acala-main-network
> Added 787 Acala main network

- constants/extraRpcs.json
},
"1":{
"rpcs":[
HTTP://127.0.0.1:8545
]
},
> create extra rpc

- constants/extraRpcs.js
Greetings
Add 13000 SPS and 14000 SPS-Testnet.
Thanks a lot.
> Add 13000 SPS and 14000 SPS-Testnet network

- constants/extraRpcs.js
> Updated 1RPC support on more chains

- components/header/header.module.css
- components/header/index.js
- components/unlock/unlock.js
- public/connectors/icn-trust.svg
- translations/en.json
- utils/index.js
> Add Trust Wallet icon

- constants/extraRpcs.js
New ZMOK.io privacy-policy since 12/16/2022
> Updated ZMOK.io privacy-policy

- components/Layout/index.js
- components/RPCList/index.js
- components/chain/index.js
- components/header/index.js
- pages/_document.js
- pages/chain/[chain].js
- pages/index.js
- pages/zh/chain/[chain].js
- pages/zh/index.js
- utils/index.js
- vercel.json
> i18n for full static site

- hooks/useAddToNetwork.jsx
- hooks/useAnalytics.js
> feat add new events on chains not yet supported

- constants/extraRpcs.js
https://BlocksRPC.io
https://xdcrpc.com
> Added extra RPC for XDC Network

- constants/extraRpcs.js
https://omniatech.io
https://omniatech.io/privacy-policy
https://blog.omniatech.io/how-omnia-handles-your-personal-data
N/A
> Add Omnia endpoints for Aurora, Fantom and ETH Sepolia.

- constants/extraRpcs.js
https://liveplex.io
https://www.liveplex.io/privacypolicy.html
> add Liveplex OracleEVM RPC

- constants/extraRpcs.js
Provider: https://unitedbloc.com
Privacy: https://unitedbloc.com/privacy-statement
> Adding UnitedBloc rpcs

- constants/extraRpcs.js
> Added more RPC url for Bitgert chain

- constants/extraRpcs.js
https://onfinality.io
https://onfinality.io/privacy
> Add OnFinality Moonbeam APIs, replace private Moonriver endpoint with public

- constants/extraRpcs.js
Adding a new public RPC for Cronos from BlockPI Network, thanks.
> Add public RPC for Cronos from BlockPI Network

- constants/chainIds.json
- constants/extraRpcs.js
https://rpc-testnet.hika.network/
https://www.freeprivacypolicy.com/live/6cdb5530-ed1b-4db9-9e27-3d76344d9a93
> Add Hika Chain RPC Devnet

- constants/extraRpcs.js
Klaytn RPCs update
List of available endpoint nodes: https://docs.klaytn.foundation/content/dapp/json-rpc/public-en
> Klaytn RPCs update

- constants/extraRpcs.js
I just added it from [https://chainlist.org/zh?search=enuls](https://chainlist.org/zh?search=enuls), I need it in the DefiLlama Adapters.
> add RPC for enuls

- constants/chainIds.json
- constants/extraRpcs.js
https://www.coredao.org
https://www.coredao.org/privacy
> add core blockchain

- constants/extraRpcs.js
> ADD ATOSHI_RPC

- constants/extraRpcs.js
Ethereum, BNB, Moonbase Alpha
http://onfinality.io
https://onfinality.io/privacy
> Update extraRpc.js with OnFinality endpoints

- constants/extraRpcs.js
Privacy statement already there for OnFinality
> Added OnFinality Polygon API

- constants/extraRpcs.js
> Fixed OnFinality Avalanche Endpoint

- constants/extraRpcs.js
Add Alchemy's Sepolia testnet. Lmk of any questions, thanks
> Add Sepolia testnet

- constants/chainIds.json
- constants/extraRpcs.js
https://infstones.com/
https://infstones.com/terms/privacy-notice
> Add new RPC endpoint of Core MainNet 

- constants/chainIds.json
- constants/extraRpcs.js
https://omaxcoin.com/
https://omaxcoin.com/Whitepaper/OMAX_Whitepaper.pdf This is a link to our whitepaper. You can find the privacy policy there
> Add omaxchain to constants/chainIds.json and constants/llamaNodesRpcs.json

- constants/extraRpcs.js
Onfinality privacy policy is already set
> Added Fantom OnFinality endpoint

- constants/extraRpcs.js
> Update extraRpcs.js - add Filecoin main net RPC node

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Karura

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Edgeware

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Darwinia Crab

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Acala

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Gnosis

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Evmos

- constants/extraRpcs.js
> Add OnFinality RPC endpoint for Harmony

- constants/extraRpcs.js
https://www.ankr.com/
https://www.ankr.com/docs/privacy/
> Add Ankr's Polygon zkEVM RPC

- constants/extraRpcs.js
Updates list of available RPC to include the latest RPC in town (MEV Blocker).
> Updates list to include MEV Blocker RPC

- constants/extraRpcs.js
https://cloud.chainup.com/
We only collect user IP addresses for the purpose of rate limiting. For more information, please visit https://docs.chainupcloud.com/introduction/products/blockchain-api.
> Add Filecoin API And ChainupCloud Policy

- constants/extraRpcs.js
> update etc-network.info ERIGON RPCs & privacy statement

- constants/extraRpcs.js
add filecoin mainnet RPC node https://infura.sftproject.io/filecoin/rpc/v1
> Update extraRpcs.js -  add filecoin mainnet RPC node by sftprotocol

- constants/extraRpcs.js
> Add OnFinality RPC Endpoint for Arbitrum

- constants/extraRpcs.js
https://gateway.fm/
https://gateway.fm/privacy-policy/
> Add gateway.fm RPC for Ethereum, Goerli, Fantom, Polygon zkEVM

- components/chain/index.js
- pages/chain/[chain].js
This pr add add chain id hex value to chain card.
> add chain id hex value

- constants/extraRpcs.js
> Add OnFinality Endpoint for Optimism

- components/Layout/index.js
> Fix JXS props to eliminate warnings

- constants/chainIds.json
- constants/extraRpcs.js
- Add chainid on `chainids.json`
- Add extra RPCS `POKT`
- https://www.pokt.network/
- https://www.blog.pokt.network/rpc-logging-practices/
> Update Oasys Chain ID and RPC

- constants/extraRpcs.js
https://jfinchain.com
https://j2o.io/
https://raw.githubusercontent.com/jfinchain/node/main/jfc-policy.html
> add Jfinchain / J2o 

- constants/extraRpcs.js
Protocol Labs https://protocol.ai/
We currently haven't got a privacy policy hosted, we'll add one in the future and create a second PR to update it. It won't be semantically different to what we're submitting in this PR.
> Add chain.love rpc for filecoin

- constants/extraRpcs.js
> add eth-sepolia of unifra

- constants/chainIds.json
> add carbon evm chain logo to mapping

- constants/extraRpcs.js
> Add OnFinality Endpoint for DFK Chain

- constants/extraRpcs.js
> Add OnFinality Endpoint for Fuse

- constants/llamaNodesRpcs.js
- hooks/useAddToNetwork.jsx
Custom LlamaNodes wallet network name
> feat: custom names LlamaNodes

- constants/extraRpcs.js
https://neon-mainnet.everstake.one
> Update extraRpcs.js added Everstake url

- constants/extraRpcs.js
> fix comma and brackets typo

- constants/extraRpcs.js
> Fix typo in extraRpcs.js

- constants/extraRpcs.js
> Add OnFinality Endpoint for Klaytn

- constants/extraRpcs.js
> Add OnFinality Endpoint for Celo

- constants/extraRpcs.js
Add DRPC public endpoints  - eth, polygon
In progress
> Update extraRpcs.js - Add DRPC public endpoints

- constants/chainIds.json
- constants/extraRpcs.js
https://xdcrpc.com
None
Updated RPCs at Ethereum-Lists
https://github.com/ethereum-lists/chains/pull/2938
https://github.com/ethereum-lists/chains/pull/2937
> Add Extra RPCs for XDC MainNet & TestNet

- constants/extraRpcs.js
> Current drpc link update

- constants/extraRpcs.js
1. Add ChainX rpcs
2. Remove SherpaX rpc which is about to be shut down
https://chainx.org/
> Add ChainX rpcs

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for base-goerli

- components/AdBanner/index.js
> remove brave from rotation

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for op-goerli

- constants/extraRpcs.js
1RPC doc has migrated to https://docs.1rpc.io/technology/zero-tracking
> Update 1RPC doc link for zero tracking

- constants/extraRpcs.js
OnFinality privacy policy provided
> Add OnFinality RPC Endpoint for Kava

- constants/extraRpcs.js
https://node.filutils.com/rpc/v1
> add https://node.filutils.com/rpc/v1 rpc

- constants/extraRpcs.js
> Update chainid=1501 rpc urls

- constants/extraRpcs.js
https://blockchain.or.th
https://blockchain.or.th/privacy-policy/
> Add TBSI RPC endpoints

- constants/extraRpcs.js
> Update extraRpcs with new blockpi public endpoint for Base-Mainnet

- components/Tooltip/index.js
- package.json
- yarn.lock
> refactor: add clickable link in tooltip

- components/AdBanner/index.js
- utils/index.js
> fix: banner random + hydration

- components/AdBanner/index.js
> feat update utm url for Brave

- constants/extraRpcs.js
main RPCs were already added in https://github.com/ethereum-lists/chains/pull/3261
this PR: 
- adds extra beta RPC
- removed legacy RPC
> update acala RPCs

- constants/extraRpcs.js
Changing from https://1rpc.io/zkevm  to https://1rpc.io/polygon/zkevm
> Update 1RPC Polygon zkEVM endpoint URL

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for Scroll-Sepolia and Linea

- constants/extraRpcs.js
https://meowrpc.com/
https://privacy.meowrpc.com/
> Add zksync.meowrpc.com

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for tomochain

- constants/extraRpcs.js
> add unifra RPC to scroll-sepolia

- constants/extraRpcs.js
https://pon.network/
```
Blockswap RPC does not track any kind of user information (i.e. IP, location, etc.) nor is any information logged. All blocks are encrypted when passed between proposers, builders, relayers, and Ethereum. It does not transmit any transactions to the relayer.
```
> Blockswap Goerli Builder RPC

- constants/extraRpcs.js
- https://www.ankr.com/rpc/scroll/
- https://www.quicknode.com/
- https://01node.com/
- https://chainstack.com/
> Add Scroll Sepolia testnet extra RPC URLs

- constants/extraRpcs.js
> New endpoints for 12 chains

- components/AdBanner/index.js
- constants/hypelab.js
- hooks/useAnalytics.js
- package-lock.json
- package.json
- pages/index.js
- yarn.lock
Working with Charlie to insert a HypeLab programmatic banner slot. Modifications:
* Added HypeLab React SDK
* Modified AdBanner design to use Native format + responsive design
* Removed Fathom banner tracking
Questions:
* Do we need to track clicks in Fathom? If so, is it possible to have one click event ID and simply pass a property string to differentiate ads?
> Swapping out Chainlist banner with HypeLab banner

- constants/extraRpcs.js
https://omniatech.io/
https://omniatech.io/privacy-policy/
https://blog.omniatech.io/how-omnia-handles-your-personal-data
N/A
> Add new Omnia RPCs

- constants/extraRpcs.js
> modify 'http' to 'https'

- constants/chainIds.json
- constants/extraRpcs.js
**Note:** These are replacements of old shardeum network details
> Add Shardeum Testnet RPCs

- constants/extraRpcs.js
> Add OnFinality RPC Endpoints for Metis and IoTex

- constants/extraRpcs.js
> Add OnFinality RPC Endpoint for OKT-Chain

- constants/extraRpcs.js
https://softnote.com
https://tectum.io/privacy/
> Update extraRpcs.js TECTUM

- constants/extraRpcs.js
https://chainstack.com/
Chainstack's privacy policy: 
https://chainstack.com/privacy/
> Kava updates

- constants/extraRpcs.js
Service provider: [Ankr](https://www.ankr.com/)
Privacy policy: [Linked](https://www.ankr.com/privacy-policy/)
> Add Mantle RPC by Ankr Provider

- constants/chainIds.json
- constants/extraRpcs.js
https://chainlist.org/chain/169
https://pacific.manta.network/
> add manta pacific chain

- constants/extraRpcs.js
> Add OnFinality RPC Endpoints for Shiden, Karura, Base, Klaytn and Fantom

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for arbitrum-sepolia

- constants/extraRpcs.js
https://pollum.io/
The RPCs are public.
N/A
> Added Pollum Rpc for rollux mainnet and testnet

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for scroll

- constants/extraRpcs.js
> added IcecreamSwap RPC for Scroll chain

- constants/extraRpcs.js
https://merkle.io
merkle is a crypto infrastructure company, and started offering a ultra fast, 100% free RPC last week: 
https://twitter.com/MerkleFinance/status/1712935063438938431
https://www.notion.so/merkle3/Privacy-Policy-4cdec69d4e01469cb274c230e05eff90?pvs=4
> Adding eth.merkle.io RPC service

- constants/extraRpcs.js
> Add iChain RPC

- components/header/index.js
> Adjusting the focus of the input

- constants/extraRpcs.js
> updates notadegen.com rpc endpoints

- constants/extraRpcs.js
Added liquify fuse rpc
https://liquify.io
https://www.liquify.io/privacy_policy.pdf
> Add liquify fuse endpoint

- constants/extraRpcs.js
POKT's endpoints are being updated on November 1st per this blog post https://www.pokt.network/deprecation-of-rpc-endpoints-what-you-need-to-know/
This PR removes all deprecated endpoints and adds all new endpoints.
> Updating POKT's Endpoints

- constants/extraRpcs.js
Website: [DragonStake](https://dragonstake.io)
Explorer: [UniChain](https://unicha.in)
> Add 9000 and 9001 extra rpcs

- constants/extraRpcs.js
> Added jsonrpc for Evmos mainnet

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for viction

- constants/extraRpcs.js
> Add AutoStake Evmos jsonrpc's

- constants/extraRpcs.js
> Add Validatrium  Evmos endpoint

- constants/extraRpcs.js
https://lokibuilder.xyz
https://lokibuilder.xyz/privacy
> Add lokibuilder

- constants/extraRpcs.js
https://cyphercore.io
https://cyphercore.io/privacy-policy/
> Add Cypher Core EVMOS JSONRPC

- constants/extraRpcs.js
> Add alkadeta Evmos Testnet json-rpc

- constants/extraRpcs.js
> Update extraRpcs.js add mzonder endpoints

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for base-sepolia

- constants/extraRpcs.js
> Added NetZ's New RPC

- constants/extraRpcs.js
https://unifra.io/
https://blastapi.io/
Provided in the code
> Add Scroll mainnet extra RPC URLs

- constants/extraRpcs.js
- https://rpc.mydefichain.com/
Not mine, am using Chainlist bc it's convenient to add RPCs. Otherwise it's at https://mydeficha.in/en/index.php?site=imprint
> feat(rpc): add defichain evm rpcs

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for linea-goerli

- constants/chainIds.json
- constants/extraRpcs.js
Update Hybrid Chain 2468 Mainnet
https://hybridchain.ai
https://docs.hybridchain.ai/privacy-policy
https://docs.hybridchain.ai/terms-of-use
> Update Hybrid Chain 2468 Mainnet

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for op-sepolia

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for polygon-zkevm-testnet

- constants/extraRpcs.js
https://www.ankr.com/
https://www.ankr.com/privacy-policy/
> Add ANKR RPC to CoreDAO chain

- constants/extraRpcs.js
https://services.tokenview.io
https://services.tokenview.io/en/protocol
> Add tokenview RPC service

- constants/chainIds.json
- constants/extraRpcs.js
https://rpc-l1.jibchain.net is the official RPC (I put it in the first RPC) and I don't know about the privacy policy of their service. This is the official website: [https://jibchain.net/](https://jibchain.net/).
The second one RPC (https://jib-rpc.inan.in.th) is mine, so I'm maintaining this, and I put the privacy details on the same file.
-
> Add RPCs for JIBCHAIN

- constants/extraRpcs.js
**Link the service provider's website (the company/protocol/individual providing the RPC):**
https://itrocket.net/
https://itrocket.net/services/mainnet/humans/
https://itrocket.net/services/testnet/humans/
**Provide a link to your privacy policy:**
UPD: https://itrocket.net/privacy-policy/
**If the RPC has none of the above and you still think it should be added, please explain why:**
📌 Adding Humans.AI RPCs with chain ID **1089** for mainnet and **4139** for testnet. As far as I can see, those IDs should also be defined in [chainIds.json](https://github.com/DefiLlama/chainlist/blob/main/constants/chainIds.json). If so, please consider doing it.
> add: Humans RPCs by ITRocket

- constants/extraRpcs.js
https://www.1rpc.io
https://www.1rpc.io/privacy
> Add BOBA 1Rpc endpoint

- constants/extraRpcs.js
> chore: remove dead nodes

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for Taiko-Katla

- constants/extraRpcs.js
> update: add rpc

- pages/chain/[chain].js
- pages/index.js
- pages/zh/chain/[chain].js
- pages/zh/index.js
- scripts/build-msg.js
- translations/en.json
- translations/fr.json
- translations/zh.json
Renames project from Chainlist to ChainList as per https://github.com/DefiLlama/chainlist/issues/593
> Rename to ChainList, per #593

- constants/extraRpcs.js
update kava rpcs to include ankr.
https://www.ankr.com/rpc/
See ankr privacy policy (already defined)
> Update kava rpcs

- constants/extraRpcs.js
> Update extraRpcs.js (adding Privacy policy of Nocturnode.tech)

- constants/extraRpcs.js
add ankr endpoint kava
Ankr details already in file
> add ankr endpoint kava

- constants/extraRpcs.js
https://thirdweb.com/
https://iotexrpc.com/
https://thirdweb.com/privacy
> Update IoTeX RPC

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for zksync-sepolia

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down Taiko-JoInir 

- constants/extraRpcs.js
https://www.ansybl.io
https://www.ansybl.io/privacy
> Add Ansybl Canto RPC

- constants/extraRpcs.js
> Blockpi public endpoints downline zksync-sepolia to update extraRpcs.js

- constants/extraRpcs.js
https://liquify.com
RPC privacy policy
https://www.liquify.io/Liquify_RPC_PP.pdf
> Add dymension jsonrpc by Liquify

- constants/extraRpcs.js
> Add Dymension Jsonrpc by Kynraze

- constants/extraRpcs.js
https://www.nodies.app/
https://nodestake.org/planq
https://www.nodies.app/privacy.txt
Nodestake doesn't have a privacy policy, but is a reliable endpoint provider and should be added.
> Add extra rpc to Planq

- constants/extraRpcs.js
https://www.lavanet.xyz/
https://www.lavanet.xyz/privacy-policy
> Lava eth mainnet 

- constants/extraRpcs.js
https://qki.dev/
https://qkiscan.io/
https://qki.dev/privacy.txt
> add extra  rpc

- constants/chainIds.json
- constants/extraRpcs.js
https://q.org/
https://docs.q.org/
https://explorer.q.org/
https://q.org/privacy-policy
> Add Q Mainnet RPC

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down arbitrum-goerli、optimism-goerli、zksync-era-testnet、base-goerli

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for blast

- constants/extraRpcs.js
Now using [web3-proxy](https://github.com/llamanodes/web3-proxy) for better management
> update blast.gasswap.org ws endpoint

- constants/extraRpcs.js
Related to #724, where they were added by mistake
> Remove wrong RPCs from Syscoin NEVM testnet list

- constants/extraRpcs.js
> Add Detroit Ledger Tech Telos EVM RPC Endpoint

- constants/extraRpcs.js
> Adding Tatum RPC - Aurora Mainnet

- constants/extraRpcs.js
> Adding Tatum BSC RPC node

- constants/extraRpcs.js
> Adding Tatum Avalanche C Chain Node

- constants/extraRpcs.js
> Adding Tatum BCH RPC node

- constants/extraRpcs.js
> Adding Tatum RPC Arb Nova node

- constants/extraRpcs.js
> Adding Tatum RPC Ethereum node

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for merlin

- constants/extraRpcs.js
> Adding Tatum RPC Doge

- constants/extraRpcs.js
> Addint Tatum RPC node - Fantom

- constants/extraRpcs.js
> Adding Tatum RPC Polygon node

- constants/extraRpcs.js
> Adding Tatum RPC node - OP

- constants/extraRpcs.js
> Adding Tatum RPC node - Base

- constants/extraRpcs.js
The most popular RPCs on Cronos
> Adding 2 RPC nodes - Cronos

- constants/chainIds.json
- constants/extraRpcs.js
https://bit-rock.io
https://docs.bit-rock.io
https://explorer.bit-rock.io
https://defillama.com/chain/Bitrock
> Add new RPC | Bitrock

- constants/extraRpcs.js
Egoras Technologies Limited
https://www.egochain.org
https://www.egochain.org/privacy
> Add Egochain RPC

- constants/extraRpcs.js
https://omniatech.io/
https://omniatech.io/privacy-policy/
https://blog.omniatech.io/how-omnia-handles-your-personal-data
N/A
> Add latest OMNIA RPCs

- constants/extraRpcs.js
Updated New stable XDC Network RPC's
- Added ETH Compatible WS
- Remove prefix RPCs
> Update XDC Network RPCs

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down polygon-zkevm-testnet

- constants/extraRpcs.js
Boba Network: https://boba.network
Tenderly: https://tenderly.co
Boba Network: https://boba.network/privacy-policy/
Tenderly: https://tenderly.co/privacy-policy
> Add boba Sepolia network

- constants/extraRpcs.js
> Add Polygon Bor Amoy

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for ZKfair

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for taiko-hekla

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down X1-testnet

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down goerli and polygon-mumbai

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for polygon-amoy

- constants/extraRpcs.js
> Update extraRpcs.js, added new RPC for elastos (20)

- constants/extraRpcs.js
> Added RPC - Cronos

- constants/extraRpcs.js
https://www.boraportal.com/
https://policy.boraportal.com/#privacy
> add borachain rpc

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for linea-sepolia

- constants/extraRpcs.js
> Update extraRpcs.js - Taiko.Tools

- constants/extraRpcs.js
https://www.lavanet.xyz/
https://www.lavanet.xyz/privacy-policy
> Update extraRpcs.js lava eth

- constants/extraRpcs.js
https://graffiti.farm
https://graffiti.farm/privacy-policy/
> Add Graffiti Full Node to Chainlist

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down Taiko-Katla

- constants/extraRpcs.js
https://nownodes.io/nodes
https://nownodes.io/assets/data/privacy-pol.pdf
99+ blockchain networks, trusted by tier-1 web3 projects
> Update extraRpcs.js + NOWNodes BSC&ETH

- constants/extraRpcs.js
[https://rpc.nowscan.io](https://rpc.nowscan.io)
[https://nowchain.co/privacy-policy](https://nowchain.co/privacy-policy)
> Add NOW RPC for NOW Chain

- constants/extraRpcs.js
https://www.ankr.com/rpc/taiko/taiko_hekla/
https://www.ankr.com/docs/privacy/
> Add ankr endpoint for Hekla testnet

- constants/extraRpcs.js
[](https://plyr.network)
Not finish right now. And RPC provided automaically by Avacloud Subnet solution
> Add PLYR TAU Testnet

- constants/extraRpcs.js
- https://rpc.ankr.com/polygon_amoy
- https://polygon-amoy.drpc.org
- https://api.tatum.io/v3/blockchain/node/polygon-amoy
- https://www.ankr.com/docs/privacy/
- https://drpc.org/privacy-policy
- https://tatum.io/privacy-policy
> add more amoy rpc

- constants/extraRpcs.js
https://envelop.is/
https://docs.envelop.is/legal/privacy-policy
> Envelop RPC for Blast Mainnet

- constants/extraRpcs.js
> Update extraRpcs.js:new endpoint for taiko mainnet

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for taiko-mainnet

- constants/extraRpcs.js
> Added Lycan Chain extraRpcs.

- constants/extraRpcs.js
https://radiumblock.com/
https://radiumblock.com/privacy.html
> Update extraRpcs.js - Add RadiumBlock public endpoints for Astar/Shiden and Moonbeam/Moonriver

- constants/extraRpcs.js
Adding RadiumBlock public eth RPC
https://radiumblock.com/
https://radiumblock.com/privacy.html
> Update extraRpcs.js add RadiumBlock public eth endpoint

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down Linea-Goerli

- constants/extraRpcs.js
> Add PublicNode RPC for Blast

- constants/extraRpcs.js
> Update extraRpcs.js for LUKSO Mainnet

- constants/extraRpcs.js
> bahamut rpc endpoint added

- constants/extraRpcs.js
https://glscan.io/
https://glscan.io/Policy
> Proposal to add GLC rpc's

- constants/extraRpcs.js
https://www.nal.network/
https://www.nal.network/privacy.html
> Add nal testnet

- constants/extraRpcs.js
Adding Blast API in IOTA testnet
> Update extraRpcs.js - Adding Blast API in IOTA testnet

- constants/extraRpcs.js
> feat: 🎸 Added bArtio testnet RPC

- constants/extraRpcs.js
> rpc endpoint added

- constants/chainIds.json
- constants/extraRpcs.js
> Add Etherlink Network

- constants/additionalChainRegistry/chainid-2020.js
Add faucet link for Roninchain
> Update faucet link for RoninChain

- constants/chainIds.json
- constants/extraRpcs.js
https://www.conduit.xyz 
`rpc.onchainpoints.xyz.	300	IN	CNAME	rpc-onchain-points-8n0qkkpr2j.t.conduit.xyz.`
https://www.conduit.xyz/privacy-policy
Note: Merged chainid with lists repo as well: https://github.com/ethereum-lists/chains/pull/5383
> Add Onchain Points Mainnet

- constants/extraRpcs.js
https://www.nal.network/
https://www.nal.network/privacy.html
> Add nal mainnet

- constants/extraRpcs.js
> If you are adding a new RPC, please answer the following questions.
> 
> #### Link the service provider's website (the company/protocol/individual providing the RPC):
https://porters.xyz/
> #### Provide a link to your privacy policy:
https://porters.xyz/tos
> #### If the RPC has none of the above and you still think it should be added, please explain why:
> Your RPC should always be added at the end of the array.
> Add PORTERS Taiko Mainnet public rpc endpoint

- constants/additionalChainRegistry/chainid-2020.js
Add working public Ronin RPCs and remove non-working ones.
>  Update Ronin (2020) RPCs

- constants/extraRpcs.js
https://www.dojima.network/
https://www.dojima.network/privacy-policy
Note: PR has been successfully merged on ethereum-lists/chains repo: https://github.com/ethereum-lists/chains/pull/5456
> 🎸 Added Dojima Mainnet and Testnet RPC

- constants/extraRpcs.js
> Remove Project Pi PulseChain RPC

- constants/extraRpcs.js
https://blastapi.io/
https://blastapi.io/privacy-policy
> Adds Mande rpc

- constants/extraRpcs.js
Just changed the endpoint for specific RPC nodes, since we changed the naming.
> Tatum RPC Node Changes

- constants/extraRpcs.js
I'm the owner of the domain inan.in.th and I've changed the RPC endpoint a long with this PR
The old endpoint will be terminated and use the new one instead.
I also PR this change to ethereum-lists/chains, and it already been merged: https://github.com/ethereum-lists/chains/pull/5586/files
> update rpc for jibchain

- constants/chainIds.json
- constants/extraRpcs.js
https://bifrost.io/
https://bifrost.io/legal/privacy-policy
> Add Bifrost Polkadot Mainnet

- constants/chainIds.json
- constants/extraRpcs.js
https://changcoin.foundation/
https://changcoin.foundation/
--
FYI: This is a new chain that just added to the chainid.network recently. https://chainid.network/chain/5858/
> Add New Chain - Chang Coin Foundation (5858)

- constants/extraRpcs.js
https://soneium.org/en/
https://www.sonynetwork.co.jp/sonynetworkcomlabs/en/privacy-policy/
> Add Soneium Minato Testnet

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for Klaytn

- constants/extraRpcs.js
> Update extraRpcs.js - Add RPC EVM testnet for Story Protocol

- constants/chainIds.json
> Update Zircuit chainID

- constants/extraRpcs.js
**Link the service provider's website (the company/protocol/individual providing the RPC):** https://mandragora.io
**Provide a link to your privacy policy:**
**If the RPC has none of the above and you still think it should be added, please explain why:**
> Update extraRpcs.js - Add RPC EVM testnet for Story Protocol (Mandragora)

- constants/chainIds.json
After adding it, the scroll icon will show in https://chainlist.org/?search=scroll
> Add scroll to chainIds.json

- constants/chainIds.json
After adding it, the dymension icon will show in https://chainlist.org/?search=dymension
> Add dymension to chainIds.json

- constants/extraRpcs.js
https://service.josephtran.xyz/testnet/story/services
https://service.josephtran.xyz/testnet/privacy-policy
Although I have provided a privacy policy link, I'd like to emphasize that this RPC node adheres strictly to best practices in data protection. No personal data is collected or stored from RPC requests. The node only processes blockchain-related queries without retaining any user-specific information. I'm committed to maintaining the integrity and security of the Story testnet.
> Add Story Testnet RPC

- constants/extraRpcs.js
> added BlockHub JSON-RPC for Story Protocol

- translations/fr.json
added French internationalization key
> docs: added French internationalization key

- translations/zh.json
> docs: improve Chinese translation

- constants/extraRpcs.js
> Add: itrocket story RPC

- constants/extraRpcs.js
> Add: Grand Valley's story RPC

- constants/extraRpcs.js
> Add aldebaranode story testnet rpc

- constants/extraRpcs.js
https://callstatic.com
https://callstatic.com/privacy-policy/
\-
> Introduce callStatic mainnet RPCs

- constants/extraRpcs.js
https://service.josephtran.xyz/testnet/vana/services
https://service.josephtran.xyz/testnet/privacy-policy
Although I have provided a privacy policy link, I'd like to emphasize that this RPC node adheres strictly to best practices in data protection. No personal data is collected or stored from RPC requests. The node only processes blockchain-related queries without retaining any user-specific
> Update VANA Testnet RPC

- constants/extraRpcs.js
See #1294. We've changed how we are handling request data.
> Update callStatic privacy statement

- constants/chainIds.json
- constants/extraRpcs.js
> add matchain

- constants/extraRpcs.js
> Bc Hyper chain rpc added and it's privacy policy declaration

- constants/extraRpcs.js
https://glideprotocol.xyz/
https://glideprotocol.xyz/terms-conditions
Glide Protocol has been added in https://chainid.network/
https://chainid.network/chain/251/
https://chainid.network/chain/253/
> add Glide Protocol

- constants/extraRpcs.js
Updated RPC Endpoint Urls
Reference: https://docs.kaia.io/references/public-en/
https://docs.kaia.io/references/public-en/
> Updated Kaia RPC endpoints

- constants/extraRpcs.js
> Added dRPC new endpoints

- constants/extraRpcs.js
https://zan.top/home/node-service
https://a.zan.top/static/Privacy-Policy.pdf
ZAN Node Service now supports an expanded range of blockchain networks and offers a more streamlined public RPC service URL.
> Update extraRpcs.js for ZAN RPC

- constants/chainIds.json
- constants/extraRpcs.js
https://www.aiachain.org
aiachain has been added to the chainlist，https://chainlist.org/chain/1319
> add aiachain and RPCs

- constants/extraRpcs.js
missed typo brakes extraRpcs.js
> Fix typo - missed comma before BlockRazor block

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down zkfair 

- constants/additionalChainRegistry/chainid-33139.js
- constants/chainIds.json
- constants/extraRpcs.js
> Add chain: Ape

- constants/extraRpcs.js
https://nodeinfra.com/
https://nodeinfra.com/company-terms
> Add Nodeinfra story testnet rpc

- constants/chainIds.json
- constants/extraRpcs.js
> Add DreyerX chain

- constants/extraRpcs.js
https://omniatech.io/
https://omniatech.io/privacy-policy/
https://blog.omniatech.io/how-omnia-handles-your-personal-data
N/A
> Add latest Omnia RPCs.

- constants/extraRpcs.js
> fix rpc for matchain

- constants/extraRpcs.js
> Add story evm rpc

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint down taiko 

- constants/extraRpcs.js
https://sophon.xyz
https://docs.sophon.xyz
https://sophon.xyz/privacypolicy.html
N/A
> Update extraRpcs.js - adding Sophon networks

- constants/chainIds.json
- constants/extraRpcs.js
> Add ink sepolia

- constants/extraRpcs.js
> added BlockHub's Story Protocol RPC

- constants/extraRpcs.js
> Updated extraRpcs.js

- constants/extraRpcs.js
https://drpc.org/chainlist/apechain
> APEChain update | Update extraRpcs.js

- constants/extraRpcs.js
> Update extraRpcs.js by 🔥STAVR🔥

- constants/extraRpcs.js
Adding Story RPC
https://rawaki.xyz/
We have exprienced to provide our EVM and Cosmos RPC
> Adding Story RPC from Rawaki

- constants/extraRpcs.js
https://vanarchain.com/
https://vanarchain.com/en/privacy-policy.html
> Update extraRpcs.js with Vanar RPCs

- constants/extraRpcs.js
[- Ankr](https://www.ankr.com/)
[- Conduit](https://www.conduit.xyz/nodes)
Already added
> feat: added corn maizenet and testnet

- constants/extraRpcs.js
- [Histori Archival MultiNode](https://docs.histori.xyz/docs/archive-node-info/intro)
- [Privacy Policy](https://histori.xyz/support/privacy-policy)
> Histori MultiNode RPC urls

- constants/extraRpcs.js
Website of the provider: https://www.1000x.ch/
Reason to add it:
MintMe Network has not many Geth nodes and the official node is sometimes slow. My node runs now for more than 3 years and I would like to shear the existent of it with more people.
RPC: https://node.1000x.ch
> Added my own RPC node to the list.

- constants/extraRpcs.js
https://app.numa.network/
https://app.numa.network/privacy-policy/
> added numa rpc

- constants/extraRpcs.js
> Added RPC to chain-id 1516

- constants/extraRpcs.js
Reverts DefiLlama/chainlist#1417
> Revert "Added RPC to chain-id 1516"

- constants/extraRpcs.js
> Update extraRpcs.js with new blockpi public endpoint for story-odyssey

- constants/extraRpcs.js
> Update extraRpcs.js with blockpi public endpoint

- constants/extraRpcs.js
https://memecore.com/
https://docs.memecore.com/support/mine-to-earn-terms-of-service
> add MemeCore Formicarium testnet rpc

- constants/chainIds.js
- constants/extraRpcs.js
> feat: added Corn rpcs and chain id

- constants/extraRpcs.js
https://j-node.net/testnet/vana/services
https://service.josephtran.xyz/privacy-policy/
Although I have provided a privacy policy link, I'd like to emphasize that this RPC node adheres strictly to best practices in data protection. No personal data is collected or stored from RPC requests. The node only processes blockchain-related queries without retaining any user-specific information. I'm committed to maintaining the integrity and security of the Story testnet.
> Add Vana Mainnet EVM RPC | JosephTran

- constants/chainIds.js
- constants/extraRpcs.js
https://www.quicknode.com/
https://www.gelato.network/
> Adding in Ink Mainnet Information

- constants/chainIds.js
- constants/extraRpcs.js
https://www.altlayer.io/
https://hsk.xyz/legal/disclaimer
> feat: add HashKey Chain

- constants/extraRpcs.js
https://spidernode.net/
Pre-add rpc for prepare mainnet happen soon. Chain already registered.
> Add Story mainnet rpc

- constants/extraRpcs.js
https://auranode.xyz/
Add extra RPC Odyssey Testnet. Chain already registered.
> [Auranode] add rpc story odyssey

- constants/extraRpcs.js
For Mainnet RPCs
1.	https://metis.rpc.hypersync.xyz/
•	Service Provider Website: [HyperSync](https://hypersync.xyz/)
•	Privacy Policy: No explicit policy found.
•	Reason for Adding: Reliable infrastructure for blockchain nodes, ensuring redundancy.
2.	https://metis-pokt.nodies.app/
•	Service Provider Website: [POKT Network](https://www.blog.pokt.network/)
•	Privacy Policy: [POKT Privacy Policy](https://www.blog.pokt.network/rpc-logging-practices/)
•	Reason for Adding: Decentralized and privacy-preserving RPC infrastructure.
3.	https://api.blockeden.xyz/metis/67nCBdZQSH9z3YqDDjdm
•	Service Provider Website: [BlockEden](https://blockeden.xyz/)
•	Privacy Policy: No explicit policy found.
•	Reason for Adding: Reliable and …
> Metis Mainnet and Testnet RPCs added

- constants/extraRpcs.js
https://onfinality.io/networks/arbitrum-sepolia
Already disclosed
> Added OnFinality Arbiturm Sepolia

- constants/extraRpcs.js
> Add Story mainnet RPC | J-Node

- constants/extraRpcs.js
**Link the service provider's website (the company/protocol/individual providing the RPC):** https://mandragora.io
**Provide a link to your privacy policy:**
**If the RPC has none of the above and you still think it should be added, please explain why:**
> Update Mandragora's Odyssey's Story's testnet RPC endpoint

- constants/extraRpcs.js
> Add: ITRocket services for 0G

- constants/chainIds.js
- constants/extraRpcs.js
[https://worldmobiletoken.com](url)
[https://worldmobiletoken.com/privacy-policy](url)
_Our RPC is critical for developers and users of WMC, and we ensure no user data is collected or stored._
> add WMC testnet rpc

- constants/extraRpcs.js
https://drpc.org/chainlist/ink
> dRPC Ink endpoints | Update extraRpcs.js

- constants/extraRpcs.js
https://onfinality.io/networks/optimism-sepolia
Already disclosed
> Added OnFinality Optimism Sepolia

- constants/extraRpcs.js
> Added dRPC Monad testnet RPC

- constants/extraRpcs.js
> added dRPC's Merlin endpoints | Update extraRpcs.js

- constants/extraRpcs.js
https://github.com/hubofvalley
> add Grand Valley's Story Mainnet rpc

- constants/extraRpcs.js
> Remove Envelop Blast node

- constants/extraRpcs.js
> Added dRPC Soneium and Abstract RPC endpoints 

- constants/extraRpcs.js
https://www.ankr.com/rpc/matchain/
> Add ankr public RPC to Matchain Mainnet

- constants/extraRpcs.js
[https://owlracle.info](https://owlracle.info)
[https://owlracle.info/privacy](https://owlracle.info/privacy)
> Added owlracle Proxy Nodes to RPC list.

- constants/chainIds.js
> Add darwinia mapping

- constants/extraRpcs.js
> Add silent validator RPC for Story mainnet

- constants/extraRpcs.js
http://story.foundation/
https://www.story.foundation/privacy-policy
> Add Story RPC

- constants/extraRpcs.js
> Add story rpc aeneid & mainnet Aldebaranode

- constants/extraRpcs.js
https://j-node.net/
https://j-node.net/testnet/privacy-policy/
> Add Story Aeneid testnet RPC | J-Node

- constants/extraRpcs.js
Replacing removed pol endpoint with unichain
> Add uni endpoint for 0xrpc.io

- constants/extraRpcs.js
> Added multiple RPC endpoitns | Update extraRpcs.js

- constants/extraRpcs.js
> Added OnFinality Unichain RPCs

- constants/extraRpcs.js
https://memecore.com/
https://docs.memecore.com/support/mine-to-earn-terms-of-service
> add MemeCore mainnet

- constants/extraRpcs.js
Following updates on https://0xrpc.io/
> Add Berachain & ETC RPCs

- constants/extraRpcs.js
Based on https://0xrpc.io/ updates
> Add 0xRPC MintMe endpoint

- constants/chainIds.js
- constants/extraRpcs.js
> feat: add Odyssey Testnet

- constants/additionalChainRegistry/chainid-999.js
-Main website: https://stakely.io/
- Hyperliquid EVM JSON-RPC load balancer: https://stakely.io/web3-api-load-balancer/hyperliquid?type=json-rpc
> feat: added stakely json-rpc for hyprliquid evm

- constants/extraRpcs.js
> Add: ITRocket Oraichain endpoint

- constants/extraRpcs.js
https://zksync.api.onfinality.io/public
Already disclosed
> Added Onfinality zksync

- constants/extraRpcs.js
**Link the service provider's website (the company/protocol/individual providing the RPC):** https://mandragora.io
**Provide a link to your privacy policy:**
**If the RPC has none of the above and you still think it should be added, please explain why:**
> Update Mandragora's RPC endpoint for Story mainnet (chain ID: 1514)

- constants/chainIds.js
- constants/extraRpcs.js
…stants (#1600)
www.altlayer.io for www.block-chain.lol
https://rollup-info.altlayer.io/control-court-night/block_chain_testnet
coming soon.
> Add Block Chain Testkek RPC

- constants/chainIds.js
- constants/extraRpcs.js
https://linkpool.com
No online privacy policy as generally we do not provide public RPC's, but no personal data is stored as of the message.
> Add LinkPool privacy data and Hedera mainnet node

- constants/extraRpcs.js
> added BlockHub RPC for 0G Network

- constants/llamaNodesRpcs.js
no longer operating Arbitrum, Optimism and Polygon
> remove some LlamaNodes chains

- constants/extraRpcs.js
https://murphynode.com/
We will update privacy policy to our website and update it soon
>  Add Murphy RPCs for 0G-Newton-Testnet

- constants/extraRpcs.js
https://lens.xyz/docs/chain/overview
I don't have, just for help community
I don't have, just for help community
> feat:add lens mainnet rpc

- constants/extraRpcs.js
New networks added
Website:
https://therpc.io/
RPC:
https://rpc.therpc.io/ethereum
Privacy policy:
https://therpc.io/agreement/privacy-policy
arbitrum https://rpc.therpc.io/arbitrum
sepolia https://rpc.therpc.io/arbitrum-sepolia
optimism https://rpc.therpc.io/optimism
sepolia https://rpc.therpc.io/optimism-sepolia
bsc https://rpc.therpc.io/bsc
sepolia https://rpc.therpc.io/bsc-testnet
ethereum-sepolia https://rpc.therpc.io/ethereum-sepolia
unichain https://rpc.therpc.io/unichain
sepolia https://rpc.therpc.io/unichain-sepolia
> Add TheRPC.io

- constants/extraRpcs.js
Readding it as per updates on https://github.com/0xRPC/0xRPC.github.io/commit/06abed639b7512776dd68aee0e0b2016dfece0fe
> Add 0xRPC BNB Chain node

- constants/additionalChainRegistry/chainid-999.js
> Add HyperLend RPC endpoint

- constants/extraRpcs.js
https://spidernode.net/
Add Story Aeneid RPC 
> Update story aeneid rpc

- constants/extraRpcs.js
> Update Story testnet endpoint by Cumulo

- constants/extraRpcs.js
> Update Story mainnet Cumulo endpoint

- constants/extraRpcs.js
Removing 0xRPC.io BNB node as per https://github.com/0xRPC/0xRPC.github.io/commit/844df27896ff664cbbb505342057db0f30334dcf
> Remove 0xRPC BNB node

- constants/extraRpcs.js
Network Name :- ICB Network 
Chain ID :- 73115(0x11d9b)
Currency : ICBX
Service Company = ICBX Network ( icb.network ) 
Chain Type :- Layer 1 EVM 
https://docs.icb.network/legal-docs/privacy-policy
>  ICBX Network Mainnet  New RPC's | Update extraRpcs

- constants/extraRpcs.js
add:
Story mainnet evm rpc
Story aeneid testnet evm rpc
remove
evmos testnet evm rpc
https://services.node75.org/
We dont have any. But we dont collect and process any personal data, except those, which could be extract from the blockchain
We are non-custodial professional validator and services provider. supporting decentralization in web3.
> Update extraRpcs.js 

- constants/extraRpcs.js
> [Auranode] add rpc story aeneid

- constants/additionalChainRegistry/chainid-1990.js
https://www.qie.digital/
N/A – This RPC is provided by the official QIE network infrastructure and meets the required standards for mainnet connectivity.
> Added new chain config in file name - chainid-1990.js

- constants/extraRpcs.js
https://www.bahamut.io/
https://www.bahamut.io/privacy-policy
> Add bahamut RPC urls

- constants/additionalChainRegistry/chainid-2107.js
> Add IBVM Testnet Chain (ChainId:2107)

- constants/extraRpcs.js
The RPC to be added is an alternative to the public RPC managed by Monad
> feat: add Monad Testnet Ankr RPC

- constants/extraRpcs.js
Updated the RPS addresses
Website:
https://therpc.io/
Privacy policy:
https://therpc.io/agreement/privacy-policy
> Updated RPS addresses TheRPC.io

- constants/additionalChainRegistry/chainid-9030.js
https://www.qubetics.com/
https://www.qubetics.com/privacy-policy
> PR: Add qubetics chain 

- constants/additionalChainRegistry/chainid-4048.js
Just added the chain details, not RPC.
Here are URLs related to us:
Website: https://gpu.net
Explorer: https://ganscan.gpu.net
Our products: https://subnet.gpu.net https://dapp.gpu.net https://token.gpu.net
> Added GANchain L1 Specs

- constants/additionalChainRegistry/chainid-2105.js
> Add IBVM Mainnet Chain (ChainId:2105)

- constants/additionalChainRegistry/chainid-688688.js
- https://github.com/ethereum-lists/chains/pull/7529
> Add Pharos Testnet chain configuration

- constants/additionalChainRegistry/chainid-8721.js
Adding EB-Chain to chainlist registry.
Network Information:
- Chain ID: 8721
- RPC URL: https://rpc.ebcscan.net
- Block Explorer: https://ebcscan.net
- Status: Live
The network is production-ready and fully EVM compatible.
> Add EB-Chain (Chain ID: 8721)

- constants/additionalChainRegistry/chainid-299792.js
- constants/additionalChainRegistry/chainid-299892.js
[t1protocol](https://t1protocol.com/)
No privacy policy yet
The RPCs are currently offline and the missing data will be added once available.
> feat: add t1 mainnet and testnet

- constants/extraRpcs.js
https://caldera.xyz/
https://portal.caldera.xyz/apechain
https://curtis.hub.caldera.xyz/
https://portal.caldera.xyz/manta-sepolia
https://portal.caldera.xyz/manta-pacific
Not mine, can ask, doesn't mention rpcs.
https://caldera.xyz/privacy
> Updated caldera rpc endpoints

- constants/additionalChainRegistry/chainid-181228.js
- constants/additionalChainRegistry/chainid-190415.js
https://docs.hpp.io/getting-started/network-information
The mainnet is in private. It will be public on docs next week.
N/A
> Add HPP Sepolia (chainid : 181228), HPP Mainnet (chainid : 190415)

- constants/additionalChainRegistry/1233.json
- constants/additionalChainRegistry/chainid-1233.js
Adds Fitochain (chainId 1233) to Chainlist.
- Website: https://fitochain.com
- RPC: https://rpc.fitochain.com
- Explorer: https://explorer.fitochain.com
- Native currency: FITO (18 decimals)
- Logo: https://fitotechnology.com/wp-content/uploads/2025/08/fito.svg
> Add Fitochain (chainId 1233) to Chainlist

- constants/additionalChainRegistry/chain-2201.js
add stable chain, chainId 2201
> feat(stable-2201): add stable chain, chainId 2201

- constants/additionalChainRegistry/chainid-14601.js
https://github.com/ethereum-lists/chains/pull/7607
> Add Sonic Testnet Network

- constants/extraRpcs.js
> fix: correct Abstract Sepolia chain ID from 2741 to 11124

- constants/additionalChainRegistry/chainid-838.js
https://www.conduit.xyz/
https://www.conduit.xyz/privacy-policy
> feat: add forknet rpc

- constants/additionalChainRegistry/chainid-198724.js
Adds EADX Network (chainId 198724) with RPC and EIP-3091 explorer. PoA chain supporting EIP-155.
> Add EADX Network (chainId 198724) to additional registry

- constants/additionalChainRegistry/chainid-192.js
- constants/additionalChainRegistry/chainid-92870.js
https://www.watr.org/
https://www.watr.org/privacy
> New Chain : Watr Mainnet and Testnet

- constants/extraRpcs.js
https://nodies.app; We're technically not new, but we were offering public endpoints via pokt previously. That partnership has concluded, so we are now changing the endpoints to our own instead. We also added a number of new public endpoints that were previously not included. 
https://www.nodies.app/privacy.txt
> Updated and added Nodies public endpoints

- constants/additionalChainRegistry/chain-190278.js
> Add gomchain chainlist

- constants/extraRpcs.js
https://rpc-dashboard.poolz.finance/
These RPCs provide additional redundancy, improve reliability, and help users and developers access the network with more stability and lower latency. Having multiple RPC options ensures decentralization, avoids single points of failure, and benefits the ecosystem by giving users alternatives when one endpoint is down or overloaded.
> add poolz rpcs

- constants/extraRpcs.js
This RPC was added by me. I want to update the privacy policy.
> Update pulseChain RPC privacy protocol

- constants/additionalChainRegistry/chainid-5031.js
> Fix: Updated the Somnia Mainnet Explorer

- constants/additionalChainRegistry/chainid-484.js
> feat: add Camp Mainnet

- constants/extraRpcs.js
Added new endpoints
https://nownodes.io/
https://nownodes.io/assets/data/privacy-pol.pdf
> new endpoints for NOWNodes

- constants/additionalChainRegistry/chainid-2027.js
> Adding martianchain

- constants/additionalChainRegistry/chainid-504.js
Added LightchainAI configuration file
> Created chainid-504.js

- constants/additionalChainRegistry/chainid-259251.js
- constants/additionalChainRegistry/chainid-9601.js
**Mainnet**
Name: KUB Layer 2 Mainnet
Chain ID: 9601
RPC: https://kublayer2.kubchain.io/
Explorer: https://kublayer2.kubscan.com/
**Testnet**
Name: KUB Layer2 Testnet
Chain ID: 259251
RPC: https://kublayer2.testnet.kubchain.io/
Explorer: https://kublayer2.testnet.kubscan.com/
> Add KUB Layer 2 Testnet (259251) and Mainnet chain (9601)

- constants/extraRpcs.js
https://rpc-dashboard.poolz.finance/
https://www.poolz.finance/privacy
> add `linea` rpc

- constants/additionalChainRegistry/chainid-1408.js
Add support for the zkVerify Mainnet chain (chainId 1408)
> Add VFlow Mainnet

- constants/additionalChainRegistry/chainid-5064014.js
Ethereal Mainnet is here).
testnet ref https://github.com/DefiLlama/chainlist/blob/main/constants/additionalChainRegistry/chainid-13374202.js
> feat(ethereal-mainnet): add ethereal-mainnet

- constants/additionalChainRegistry/chainid-123999.js
- constants/additionalChainRegistry/chainid-8678671.js
- constants/extraRpcs.js
> Create chainid-123999.js and chainid-8678671.js

- constants/additionalChainRegistry/chainid-613419.js
Adding Galactica Mainnet chain
> Add Galactica Mainnet

- constants/additionalChainRegistry/chainid-235235.js
- constants/additionalChainRegistry/chainid-237007.js
- constants/additionalChainRegistry/chainid-326663.js
- constants/additionalChainRegistry/chainid-7084.js
> Add My Custom Chain to Chainlist

- constants/additionalChainRegistry/chainid-7667.js
- constants/additionalChainRegistry/chainid-76672.js
Chain ID: 7667
Chain name: CarrChain Mainnet
Chain website: https://carrchain.io/
> Add CarrChain Mainnet and Testnet

- constants/additionalChainRegistry/chainid-8765.js
Adding Warden Protocol network
> Add Warden Protocol

- constants/additionalChainRegistry/chainid-8765.js
Accidentally added wrong RPC endpoints
> Fix Warden Protocol RPC endpoints

- constants/additionalChainRegistry/chainid-24101.js
https://incentiv.io/
https://incentiv.io/privacy-policy/
> Add Incentiv Mainnet
